import Head from 'next/head'
import styles from './uploader.module.css'
import Layout from '@/components/Layout'
import { useState } from 'react'
import { collection, addDoc } from 'firebase/firestore'
import { ref, uploadString, getDownloadURL } from 'firebase/storage'

export default function Uploader() {
  const [image, setImage] = useState(null);
  const [previewUrl, setPreviewUrl] = useState('');

  const handleImageUpload = async () => {
    // 画像が選択されていない場合は処理を中断
    if (!image) {
      console.error('No image selected');
      return;
    }

    // Storageへのアップロード処理
    const storageRef = ref(storage, `images/${image.name}`);
    await uploadString(storageRef, image, 'data_url');

    // 画像のURLを取得
    const downloadURL = await getDownloadURL(storageRef);
    setPreviewUrl(downloadURL);
  };

  const handleImageChange = (e) => {
    const selectedImage = e.target.files[0];
    setImage(selectedImage);

    // 画像のプレビューを表示
    const reader = new FileReader();
    reader.onload = () => {
      setPreviewUrl(reader.result);
    };
    reader.readAsDataURL(selectedImage);
  };

  return (
    <>
      <Head>
        <title>更新画面</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Layout>

      <main className={styles.main}>
        <div className={styles.form}>
          <input type="file" onChange={handleImageChange} />
          {previewUrl && <img src={previewUrl} alt="Image Preview" />}
          <button onClick={handleImageUpload}>送信</button>
        </div>
      </main>

      </Layout>
    </>
  )
}
